---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - vim
        - mc
        - mlocate
        #- tmux

- name: copy authorized_keys file
    copy:
      src: files/authorized_keys
      dest: /usr/emile/.ssh/authorized_keys
      owner: emile
      group: emile

- name: copy authorized_keys file
    copy:
      src: files/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: emile
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: emile
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/emile/.bashrc
     owner: emile
     group: emile


  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /root/.bashrc
     owner: root
     group: root

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Milio64/setup.git
