---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - vim
        - mc
        - mlocate
        #- tmux


  - name: "install oh-my-bash1"
    ansible.builtin.shell:
      cmd: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" && sed -i 's/"font"/"agnoster"/' .bashrc
      chdir: /root
      creates: .osh-update

  - name: "Clone oh-my-bash for user Emile"
    ansible.builtin.shell:
      cmd: "git clone --depth=1 https://github.com/ohmybash/oh-my-bash.git && chown -R emile:emile /home/emile/oh-my-bash/"
      chdir: /home/emile
      creates: /home/emile/oh-my-bash/tools/install.sh

  - name: "beheer van keys voor root"
    authorized_key: user=root key="{{ lookup('file', item) }}" state=present
    with_fileglob:
      - ./files/ssh/*.pub
  - name: "add key voor Emile"
    authorized_key: user="emile" key="{{ lookup('file', item) }}" state=present
    with_fileglob:
      - ./files/ssh/*.pub
  - name: "remove keys voor Emile"
    authorized_key: user="emile" key="{{ lookup('file', item) }}" state=absent
    with_fileglob:
      - ./files/ssh/remove/*.pub
  - name: "remove keys voor root"
    authorized_key: user="root" key="{{ lookup('file', item) }}" state=absent
    with_fileglob:
      - ./files/ssh/remove/*.pub

  - name: Check grafisch omgeving ja/nee
    shell: readlink -f /etc/systemd/system/default.target
    register: shell_output

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root
    when: shell_output.stdout == "/usr/lib/systemd/system/graphical.target"

  - name: set wallpaper
    become_user: emile
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"
    when: shell_output.stdout == "/usr/lib/systemd/system/graphical.target"

  - name: set wallpaper position
    become_user: emile
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
    when: shell_output.stdout == "/usr/lib/systemd/system/graphical.target"

  # - name: copy .bashrc file1
  #   copy:
  #    src: files/bashrc
  #    dest: /home/emile/.bashrc
  #    owner: emile
  #    group: emile


  # - name: copy .bashrc file2
  #   copy:
  #    src: files/bashrc
  #    dest: /root/.bashrc
  #    owner: root
  #    group: root

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Milio64/setup.git
