---
- name: Ansible Variable Example Playbook
  hosts: localhost
  tasks:


    # display the variable data type
    - debug:
        msg: 
          - " Data type of 'ansible_architecture'  is {{ ansible_architecture | type_debug }} "
          - " Data type of 'ansible_apparmor' is {{ ansible_apparmor | type_debug }} "
          - " Data type of 'ansible_all_ipv4_addresses' is {{ ansible_all_ipv4_addresses | type_debug }} "

    # Simply printing the value of fact which is Ansible UnSafe Text type
    - debug:
        msg: "{{ ansible_architecture }}"


    # Accessing an element of dictionary
    - debug:
        msg: "{{ansible_apparmor.status}}"

    # Accessing the list
    - debug:
        msg: "{{ansible_all_ipv4_addresses}}"
      when: ansible_default_ipv4.macaddress == "00:50:08:08:35:b8" and ansible_env.HOSTNAME == "rocky-mood.vanzeijl.net"

    # Accessing the Second Element of the list
    - debug:
        msg: "{{ansible_all_ipv4_addresses[1]}}"
       

